### ISSUE TITLE
dropdown font selector

### ISSUE THREAD

**Issue by Joel-C-Johnson** [RUN-Collaborations/font-detect-rhl#1]
a dropdown button to select the fonts

**Comment by RUN-Projects** [comment]
- [Added on 4 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/dd4503a8893a1627b9804f8b4419286cddc88178)
- [Font-size also added on 4 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/9fa6238f426746c75253dc83b70a451ccc5b8589)
- [Changed to only list detected fonts on 15 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/c45c436f8f48fdf093cd32685c9f7e010586b6cb)
- [Graphite-enabled fonts added on 15 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/10a801cea4d4dcca47f73bac39bcf24d68a88e89)
- [Line-Height added on 15 Mar:](https://github.com/RUN-Collaborations/font-detect-rhl/commit/0c07b78d3a9d377936b373fa8e878cf115c49c58)
- [Temporary woff/woff2 examples added on 25 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/cecaaf2ebe8c350f691994a44e455b0dafab36d3) and [28 Mar](https://github.com/RUN-Collaborations/font-detect-rhl/commit/d025861574e60e052a43543791501c519656eec7)
- [Added without mui, +editable examples, +autodetect rtl, +px changed to em on 4 Apr](https://github.com/RUN-Collaborations/font-detect-rhl/commit/228ddebf7700f0bd20de5d3bf5787999715ed0a7) and [adjusted on 6 Apr](https://github.com/RUN-Collaborations/font-detect-rhl/commit/09e1fa0760b32f662a87b75f52b5367fd2309f64)
